name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Perl environment
        uses: shogo82148/actions-setup-perl@v1.2.1
        with:
          # The Perl version to download (if necessary) and use. Example: 5.30.0
          perl-version: 5
      - name: Setup OCaml
        uses: avsm/setup-ocaml@v1.0
        with:
          # Version of the OCaml compiler to initialise
          ocaml-version: 4.08.0
      - name: Compile
        run: eval $(opam env) && make
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          # A directory to store and save the cache
          path: .
